server:
  port: 8091
spring:
  redis:
    port: 6379
    host: 120.26.176.124
    password: admin123
    database: 12
  datasource:
    druid:
      url: jdbc:mysql://120.26.176.124:3306/my_shop
      # MySQL?????8.x   com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20